### PR TITLE
chore: cleaning up the build process, pending removal of the script load...

### PR DESCRIPTION
**Pull request by nesheroj**
...er usages

### CODE REVIEW

**Comment by nesheroj** [comment]
+5

**Comment by xaviserrag** [comment]
+1, please we need this.

**Comment by xaviserrag** [comment]
totally necessary, the boilerplate doesn't work

**Comment by xaviserrag** [comment]
can't work with this

**Comment by bernatmv** [comment]
FUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU!!!!

Za tole noč, za tale hip

**Comment by marchys** [comment]
...

**Pull request merged**
